Update README.md
in count_vowels there is no need to use two len, that just raise an error.

```
>>> count_vowels('test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in count_vowels
TypeError: object of type 'int' has no len()
```

```
>>> re.findall(r'[aeiou]', 'karol', re.IGNORECASE)
['a', 'o']
>>> len(re.findall(r'[aeiou]', 'karol', re.IGNORECASE))
2
>>> len(len(re.findall(r'[aeiou]', 'karol', re.IGNORECASE)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'int' has no len()
>>> return len(len(re.findall(r'[aeiou]', 'karol', re.IGNORECASE)))
  File "<stdin>", line 1
SyntaxError: 'return' outside function
```